[project]
name = "annotation"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.24",
    "loguru>=0.7.3",
    "polars>=1.27.1",
    "tqdm>=4.67.1",
]
